<?php
/*
Generated by Manuigniter v2.0
www.manuigniter.com
 */

defined('BASEPATH') or exit('No direct script access allowed');
require APPPATH . 'libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';

header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");

class habilities extends REST_Controller
{
    private $code01 = '001'; //CODIGO CORRECTO.
    private $code02 = '002'; //VALOR NO ENCONTRADO.
    private $code03 = '003'; //FALTAN PARAMETROS.
    private $code04 = '004'; //CODIGO NO CORRECTO.

    public function __construct()
    {
        parent::__construct();
        $this->load->model('Habilities_model');
        $this->load->helper('text');
        $this->load->library('upload');
    }

    public function add_post()
    {
        $name = $this->input->post('name');
        $id_champion = $this->input->post('id_champion');

        if ($name == '') {
            $this->response([
                'status' => false,
                'error' => true,
                'message' => 'ERROR',
                'system_code' => $this->code03,
            ], 400);
        } else {
            if (isset($_FILES["image"]["name"])) {

                $ultimo_id = $this->Habilities_model->get_last_id($id_champion);

                $nuevo_id = $ultimo_id > 0 ? $ultimo_id + 1 : 1;

                $hability = array(
                    'id' => $nuevo_id,
                    'champion' => $id_champion,
                    'name' => $name,
                );

                $id_hability = $this->Habilities_model->add_hability($hability);

                $habili = $this->Habilities_model->get_hability($nuevo_id,$id_champion);

                $config['upload_path'] = './resources/spells/';
                $config['allowed_types'] = 'jpg|jpeg|png|gif';
                $new_name1 = $id_champion.'-'.$nuevo_id;
                $config['file_name'] = $new_name1;

                $this->upload->initialize($config);
                if ($this->upload->do_upload('image')) {
                    $this->response([
                        'status' => true,
                        'error' => false,
                        'message' => "OK",
                        'system_code' => $this->code01,
                        'data' => $habili,
                    ], 200);
                } else {
                    $this->response([
                        'status' => false,
                        'error' => true,
                        'message' => 'ERROR: ' . $this->code04,
                        'system_code' => $this->code04,
                    ], 400);
                }
            } else {
                $this->response([
                    'status' => false,
                    'error' => true,
                    'message' => 'ERROR: ' . $this->code03,
                    'system_code' => $this->code03,
                ], 400);
            }
        }
    }
}
