<?php
/*
Generated by Manuigniter v2.0
www.manuigniter.com
 */

defined('BASEPATH') or exit('No direct script access allowed');
require APPPATH . 'libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';

header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");

class stats extends REST_Controller
{
    private $code01 = '001'; //CODIGO CORRECTO.
    private $code02 = '002'; //VALOR NO ENCONTRADO.
    private $code03 = '003'; //FALTAN PARAMETROS.
    private $code04 = '004'; //CODIGO NO CORRECTO.

    public function __construct()
    {
        parent::__construct();
        $this->load->model('Stats_model');
        $this->load->helper('text');
        $this->load->library('upload');
    }

    public function add_post()
    {
        $id_champion = $this->input->post('id_champion');
        $name = $this->input->post('name');
        $value = $this->input->post('value');
        $modifier_per_level = $this->input->post('modifier_per_level');

        if ($id_champion == '' || $name == '' || $value == '' || $modifier_per_level == '') {
            $this->response([
                'status' => false,
                'error' => true,
                'message' => 'ERROR',
                'system_code' => $this->code03,
            ], 400);
        } else {
           
            $stat = array(
                'champion' => $id_champion,
                'name' => $name,
                'value' => $value,
                'modifier_per_level' => $modifier_per_level,
            );

            $stat = $this->Stats_model->add_stat($stat);

            $get_stat = $this->Stats_model->get_stat($id_champion, $name);

            if ($get_stat) {
                $this->response([
                    'status' => true,
                    'error' => false,
                    'message' => "OK",
                    'system_code' => $this->code01,
                    'data' => $get_stat,
                ], 200);
            } else {
                $this->response([
                    'status' => false,
                    'error' => true,
                    'message' => 'ERROR: ' . $this->code04,
                    'system_code' => $this->code04,
                ], 400);
            }
        }
    }
}
